import {
  Button,
  Card,
  Checkbox,
  DatePicker,
  TimePicker,
  Divider,
  Empty,
  Form,
  Input,
  Menu,
  Modal,
  PageHeader,
  Radio,
  Select,
  Space,
  Switch,
  Table,
  Layout,
  ConfigProvider,
  TreeSelect,
  Dropdown,
  Row,
  Col,
  Cascader,
  Breadcrumb,
  Timeline,
  Upload,
  Tabs,
  Tag,
  Avatar,
  Transfer,
  Alert,
  InputNumber,
  Rate,
  Tooltip,
  Steps,
  Collapse,
  Tree,
  Badge,
  Spin,
  Pagination,
  Popover,
  Drawer,
} from 'ant-design-vue';

export function setupAntd(app) {
  app && app.use(ConfigProvider)
    .use(Button)
    .use(Form)
    .use(Input)
    .use(Modal)
    .use(Table)
    .use(Layout)
    .use(Menu)
    .use(Card)
    .use(Checkbox)
    .use(Radio)
    .use(Empty)
    .use(Divider)
    .use(Select)
    .use(Space)
    .use(Switch)
    .use(DatePicker)
    .use(TimePicker)
    .use(PageHeader)
    .use(TreeSelect)
    .use(Dropdown)
    .use(Row)
    .use(Col)
    .use(Cascader)
    .use(Breadcrumb)
    .use(Timeline)
    .use(TreeSelect)
    .use(Tabs)
    .use(Upload)
    .use(Tag)
    .use(Avatar)
    .use(Transfer)
    .use(Alert)
    .use(Tooltip)
    .use(Steps)
    .use(Collapse)
    .use(InputNumber)
    .use(Rate)
    .use(Tree)
    .use(Badge)
    .use(Spin)
    .use(Pagination)
    .use(Popover)
    .use(Drawer);
}
